### PR TITLE
Aggregate transformers

### PR DESCRIPTION
**Pull request by IanSudbery**
Pull request to address issue #11

### CODE REVIEW

**Comment by AndreasHeger** [comment]
Thanks, Ian. Have you rebuilt the documentation? This is the best way to check if the changes have no side-effects.

**Comment by IanSudbery** [comment]
Hi @AndreasHeger, I tried rebuilding the documentation, I had to disable converting the iPython notebooks because it complained about not being able to find mistune, even though mistune is installed and will import with `import mistune`

I get rather a large number of ERRORs and WARNINGS on building the docs, I don't know if any of them are relevant. How do I work out if documentation is similar enought to the old docs. Are the published docs somewhere I can diff against? Would I need to diff the plots as well?

**Comment by AndreasHeger** [comment]
Thanks, let me have go. There should be only the following errors:

https://www.cgat.org/downloads/public/CGATReport/documentation/Errors.html

(These are part of the tests to make sure that error reporting works).

**Comment by IanSudbery** [comment]
Those are the only errors present, but I can't guarentee all the plots are the same: when I said errors and warnings, I meant things being spat out by the build prosess, rather than things in the document it self.

**Pull request merged**
